version: "3.8"

services:
  cocktail-api:
    container_name: cocktails-api
    build:
      context: ./20.source/20.cocktail/mycocktails.api.cocktailApi
    image: mycocktails/api/cocktail-api
    ports:
      - ${API_PORT}:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    tty: true
    networks:
          - mycocktails_network
networks:
  mycocktails_network:
    external: true