version: "3.8"

services:
  cocktail-api:
    container_name: cocktails-api
    build:
      context: ./20.source/20.cocktail/mycocktails.api.cocktailApi
    image: mycocktailsacr.azurecr.io/mycocktails/api/cocktail-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=docker
    tty: true