/*
 * Material API
 *
 * API to manage material info.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: okarians.302.dev@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using mycocktails.api.materialApi.Converters;

namespace mycocktails.api.materialApi.Models
{ 
    /// <summary>
    /// material detail info model.
    /// </summary>
    [DataContract]
    public partial class MaterialDetailModel : IEquatable<MaterialDetailModel>
    {
        /// <summary>
        /// Gets or Sets MaterialInfo
        /// </summary>
        [DataMember(Name="materialInfo", EmitDefaultValue=false)]
        public MaterialModel MaterialInfo { get; set; }

        /// <summary>
        /// Cocktail info list.
        /// </summary>
        /// <value>Cocktail info list.</value>
        [DataMember(Name="cocktailList", EmitDefaultValue=false)]
        public List<CocktailModel> CocktailList { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class MaterialDetailModel {\n");
            sb.Append("  MaterialInfo: ").Append(MaterialInfo).Append("\n");
            sb.Append("  CocktailList: ").Append(CocktailList).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((MaterialDetailModel)obj);
        }

        /// <summary>
        /// Returns true if MaterialDetailModel instances are equal
        /// </summary>
        /// <param name="other">Instance of MaterialDetailModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MaterialDetailModel other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    MaterialInfo == other.MaterialInfo ||
                    MaterialInfo != null &&
                    MaterialInfo.Equals(other.MaterialInfo)
                ) && 
                (
                    CocktailList == other.CocktailList ||
                    CocktailList != null &&
                    other.CocktailList != null &&
                    CocktailList.SequenceEqual(other.CocktailList)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (MaterialInfo != null)
                    hashCode = hashCode * 59 + MaterialInfo.GetHashCode();
                    if (CocktailList != null)
                    hashCode = hashCode * 59 + CocktailList.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(MaterialDetailModel left, MaterialDetailModel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(MaterialDetailModel left, MaterialDetailModel right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
