version: '3'
services:
  mycocktails-db:
    container_name: cocktails-db-container
    build: .
    image: mycocktails/db/cocktail-db
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      DBNAME: mycocktails_db
      DBADMIN: mycocktails_admin
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    tty: true
    networks:
          - mycocktails_network
networks:
  mycocktails_network:
    external: true