/*
 * Cocktails API
 *
 * API to manage cocktail info.
 *
 * The version of the OpenAPI document: 0.2.7
 * Contact: okarians.302.dev@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using mycocktails.api.cocktailApi.Attributes;
using mycocktails.api.cocktailApi.Models;
using mycocktails.library.cocktailApi.Models;
using mycocktails.library.cocktailApi.Controllers;
using mycocktails.api.cocktailApi.Logics.intarfaces;
using Microsoft.Extensions.Logging;
using mycocktails.library.common.Models;
using CommonMessageModel = mycocktails.library.common.Models.CommonMessageModel;
using System.Net;

namespace mycocktails.api.cocktailApi.Controllers
{ 
    /// <summary>
    /// Search cocktail info controller.
    /// </summary>
    [ApiController]
    public class SearchCocktailController : SearchCocktailsApiController
    {
        private readonly ISearchCocktailLogic logic;
        private readonly ILogger<SearchCocktailController> logger;

        /// <summary>
        /// Constructor.
        /// </summary>
        /// <param name="logic">Logic.</param>
        /// <param name="logger">Logger.</param>
        public SearchCocktailController(
            ISearchCocktailLogic logic,
            ILogger<SearchCocktailController> logger)
        {
            this.logic = logic;
            this.logger = logger;
        }

        /// <summary>
        /// Search cocktail info.
        /// </summary>
        /// <param name="searchCocktailConditionModel">Search cocktail info request body.</param>
        /// <response code="200">Search cocktail info response.</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal Server Error</response>
        [HttpPost]
        [Route("/api/v1/cocktails/search")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<CocktailModel>))]
        [ProducesResponseType(statusCode: 400, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 401, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 409, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 500, type: typeof(CommonMessageModel))]
        public override IActionResult SearchPost([FromBody]SearchCocktailConditionModel searchCocktailConditionModel)
        {
            ApiResponse result;

            try
            {
                result = logic.SearchCocktail(searchCocktailConditionModel);
            }

            //
            catch (Exception ex)
            {
                CommonMessageModel error = new CommonMessageModel
                {
                    Msg = "An unknown error has occurred."
                };
                this.logger.LogError($"{error.Msg}");
                result = new ErrorResponse<CommonMessageModel>(HttpStatusCode.InternalServerError, error, ex.InnerException?.Message ?? ex.Message);
            }

            this.logger.LogInformation($"StatusCode: {result.StatusCode}");
            if (result.Success)
            {
                ApiResponse<List<CocktailModel>> successResponse = (ApiResponse<List<CocktailModel>>)result;
                return StatusCode((int)successResponse.StatusCode, successResponse.ResponseModel);
            }
            else
            {
                ApiResponse<CommonMessageModel> failureResponse = (ApiResponse<CommonMessageModel>)result;
                return StatusCode((int)failureResponse.StatusCode, failureResponse.ResponseModel);
            }
        }
    }
}
