/*
 * Materials API
 *
 * API to manage material info.
 *
 * The version of the OpenAPI document: 0.2.7
 * Contact: okarians.302.dev@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using Microsoft.AspNetCore.Mvc;
using mycocktails.api.materialApi.Attributes;
using mycocktails.library.materialApi.Models;
using mycocktails.api.materialApi.Logics.interfaces;
using mycocktails.library.materialApi.Controllers;
using Microsoft.Extensions.Logging;
using mycocktails.library.common.Models;
using CommonMessageModel = mycocktails.library.common.Models.CommonMessageModel;
using System.Net;

namespace mycocktails.api.materialApi.Controllers
{ 
    /// <summary>
    /// Create material api controller. 
    /// </summary>
    [ApiController]
    public class CreateMaterialController : CreateMaterialsApiController
    { 
        private readonly ICreateMaterialLogic logic;
        private readonly ILogger<CreateMaterialController> logger;

        /// <summary>
        /// Constractor
        /// </summary>
        /// <param name="logic">logic</param>
        /// <param name="logger">logger</param>
        public CreateMaterialController(
            ICreateMaterialLogic logic,
            ILogger<CreateMaterialController> logger)
        {
            this.logic = logic;
            this.logger = logger;
        }

        /// <summary>
        /// Create user mterial info.
        /// </summary>
        /// <param name="userMaterialModel">Create user material info request body.</param>
        /// <response code="201"></response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal Server Error</response>
        [HttpPost]
        [Route("/api/v1/materials/user_material")]
        [Consumes("application/json")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 400, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 401, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 409, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 500, type: typeof(CommonMessageModel))]
        public override IActionResult UserMaterialPost([FromBody]UserMaterialModel userMaterialModel)
        { 
            ApiResponse result;

            try
            {
                result = logic.CreateUserMaterial(userMaterialModel);
            }

            // catch error.
            catch (Exception ex)
            {
                CommonMessageModel error = new CommonMessageModel
                {
                    Msg = "An unknown error has occurred."
                };
                this.logger.LogError($"{error.Msg}");
                result = new ErrorResponse<CommonMessageModel>(HttpStatusCode.InternalServerError, error, ex.InnerException?.Message ?? ex.Message);
            }

            this.logger.LogInformation($"StatusCode: {result.StatusCode}");
            if (result.Success)
            {
                ApiResponse<CommonMessageModel> successResponse = (ApiResponse<CommonMessageModel>)result;
                return StatusCode((int)successResponse.StatusCode, successResponse.ResponseModel);
            }
            else
            {
                ApiResponse<CommonMessageModel> failureResponse = (ApiResponse<CommonMessageModel>)result;
                return StatusCode((int)failureResponse.StatusCode, failureResponse.ResponseModel);
            }
        }
    }
}
