/*
 * Material API
 *
 * API to manage material info.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: okarians.302.dev@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using mycocktails.api.materialApi.Attributes;
using mycocktails.api.materialApi.Models;

namespace mycocktails.api.materialApi.Controllers
{
    /// <summary>
    /// Get material api controller.
    /// </summary>
    [ApiController]
    public class GetController : ControllerBase
    { 
        /// <summary>
        /// Get material info list.
        /// </summary>
        /// <response code="200">Get material info list response.</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("/api/v1/material")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(List<MaterialModel>))]
        [ProducesResponseType(statusCode: 400, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 401, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 409, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 500, type: typeof(CommonMessageModel))]
        public virtual IActionResult MaterialGet()
        {
            return null;
        }

        /// <summary>
        /// Get material info by id.
        /// </summary>
        /// <param name="id">Material id.</param>
        /// <response code="200">Get material info response.</response>
        /// <response code="400">Bad Request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="409">Conflict</response>
        /// <response code="500">Internal Server Error</response>
        [HttpGet]
        [Route("/api/v1/material/{id}")]
        [ValidateModelState]
        [ProducesResponseType(statusCode: 200, type: typeof(MaterialDetailModel))]
        [ProducesResponseType(statusCode: 400, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 401, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 409, type: typeof(CommonMessageModel))]
        [ProducesResponseType(statusCode: 500, type: typeof(CommonMessageModel))]
        public virtual IActionResult MaterialIdGet([FromRoute][Required]int id)
        {
            return null;
        }
    }
}
