/*
 * Cocktail API
 *
 * API to manage cocktail info.
 *
 * The version of the OpenAPI document: 0.1.2
 * Contact: okarians.302.dev@gmail.com
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using mycocktails.api.cocktailApi.Converters;

namespace mycocktails.api.cocktailApi.Models
{ 
    /// <summary>
    /// 共通処理失敗時の応答電文
    /// </summary>
    [DataContract]
    public partial class CommonFailureModel : IEquatable<CommonFailureModel>
    {

        /// <summary>
        /// 処理失敗理由の種別
        /// </summary>
        /// <value>処理失敗理由の種別</value>
        [TypeConverter(typeof(CustomEnumConverter<ReasonEnum>))]
        [JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public enum ReasonEnum
        {
            
            /// <summary>
            /// Enum DBERROREnum for DB_ERROR
            /// </summary>
            [EnumMember(Value = "DB_ERROR")]
            DBERROREnum = 1,
            
            /// <summary>
            /// Enum DATAINCONSISTENCYEnum for DATA_INCONSISTENCY
            /// </summary>
            [EnumMember(Value = "DATA_INCONSISTENCY")]
            DATAINCONSISTENCYEnum = 2,
            
            /// <summary>
            /// Enum AUTHENTICATIONERROREnum for AUTHENTICATION_ERROR
            /// </summary>
            [EnumMember(Value = "AUTHENTICATION_ERROR")]
            AUTHENTICATIONERROREnum = 3,
            
            /// <summary>
            /// Enum VALIDATIONERROREnum for VALIDATION_ERROR
            /// </summary>
            [EnumMember(Value = "VALIDATION_ERROR")]
            VALIDATIONERROREnum = 4,
            
            /// <summary>
            /// Enum SYSTEMERROREnum for SYSTEM_ERROR
            /// </summary>
            [EnumMember(Value = "SYSTEM_ERROR")]
            SYSTEMERROREnum = 5
        }

        /// <summary>
        /// 処理失敗理由の種別
        /// </summary>
        /// <value>処理失敗理由の種別</value>
        [Required]
        [DataMember(Name="reason", EmitDefaultValue=false)]
        public ReasonEnum Reason { get; set; }

        /// <summary>
        /// 処理失敗メッセージ（オプション）
        /// </summary>
        /// <value>処理失敗メッセージ（オプション）</value>
        [DataMember(Name="msg", EmitDefaultValue=false)]
        public string Msg { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CommonFailureModel {\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  Msg: ").Append(Msg).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CommonFailureModel)obj);
        }

        /// <summary>
        /// Returns true if CommonFailureModel instances are equal
        /// </summary>
        /// <param name="other">Instance of CommonFailureModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CommonFailureModel other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Reason == other.Reason ||
                    
                    Reason.Equals(other.Reason)
                ) && 
                (
                    Msg == other.Msg ||
                    Msg != null &&
                    Msg.Equals(other.Msg)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    
                    hashCode = hashCode * 59 + Reason.GetHashCode();
                    if (Msg != null)
                    hashCode = hashCode * 59 + Msg.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CommonFailureModel left, CommonFailureModel right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CommonFailureModel left, CommonFailureModel right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
